version: '3'
services:
  tests:
    build:
      context: .
      args:
        - PHP_VERSION=7.4
    command: tail -f /dev/null
    environment:
      - PHPAR_PGSQL=pgsql://phpar:secret@postgres/phpar_test
      - PHPAR_MYSQL=mysql://phpar:secret@mysql/phpar_test
      - PHPAR_MEMCACHED=memcached
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    environment:
      - MYSQL_USER=phpar
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=phpar_test
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      interval: 5s
      retries: 3
      timeout: 5s
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=phpar_test
      - POSTGRES_USER=phpar
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "phpar"]
      interval: 5s
      retries: 3
      timeout: 5s
  memcached:
    image: memcached:1.4
